### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by xLink** [Cysha/PhoenixCMS#2]
need to start documenting properly what half the crap in here does :D

**Comment by NoelDavies** [comment]
If we comment our code properly with doc blocks and unit tests most of it could be automated

**Comment by xLink** [comment]
that works for the system api etc, but i mean actual human documentation

**Comment by NoelDavies** [comment]
yeah fair enough, why not build something like Laravels? it's simple and rather simple. Either that or Asgard, but they're quite similar!

**Comment by xLink** [comment]
yeah tis the idea :)

**Comment by xLink** [comment]
Started this a while back - https://github.com/Cysha/Documentation
There is a `pxcms-docs` module already, which will enable the docs to show up on the site, when we actually have a site :P
